### ISSUE TITLE
Configure used package managers

### ISSUE THREAD

**Issue by reinfi** [cheeZery/depdoc#24]
Hey folks,

I would like to use DepDoc for one of my projects, but I would only like to document composer packages not the node ones.

For my opinion this should be part of the configuration file.

I.e. for yml
```
composer: true
npm: true

or

managers:
    composer: true
    npm: true
```

Default would of course be true.
